### ISSUE TITLE
Authentifizierung mit JWT implementieren

### ISSUE THREAD

**Issue by mrdanf** [Smart-City-SoSe-2022/Bank#12]
Der JWT wird als Cookie vom Frontend an das Backend übergeben. Der JWT muss nur dekodiert und auf Gültigkeit überprüft werden. Erst wenn der JWT gültig ist, dürfen die Routen im Backend angesprochen werden.
Im JWT steht die ID des eingeloggten Nutzers. Stellt man eine Anfrage an `/portal/get` und übergibt dabei den JWT, werden alle Informationen des Nutzers ausgegeben.

- [ ] Übergabe von Frontend an Backend
- [ ] Dekodierung des JWT
- [ ] Schützen der Pfade, Zugriff nur mit JWT (Wrapper Funktion oder vorheriger Aufruf einer Kontrollmethode)

**Comment by Marckfx** [comment]
Ja und nein ich kann verschiedene Token Decodieren und benutz dieses auch hab aber probleme mit den coockies
